/**
 * ============================================================
 *  MARIO-LIKE PLATFORMER  –  Phaser 3
 *  Generated by Claude AI
 * ============================================================
 *
 *  QUICK REFERENCE – WHERE TO SWAP GRAPHICS:
 *  Search for comments starting with:
 *    [PLAYER GRAPHICS]     – player sprite / animations
 *    [ENEMY GRAPHICS]      – enemy sprite / animations
 *    [COIN GRAPHICS]       – coin sprite / animation
 *    [FRAGMENT GRAPHICS]   – fragment (key item) sprite
 *    [EXIT GRAPHICS]       – exit / goal door sprite
 *    [BACKGROUND GRAPHICS] – background tileset or image
 * ============================================================
 */

// ─────────────────────────────────────────────────────────────
//  SUPABASE CONFIG  –  vyplň po vytvoření projektu na supabase.com
// ─────────────────────────────────────────────────────────────
const SUPABASE_URL      = 'https://qtknrcqccdtfetquavtx.supabase.co';
const SUPABASE_ANON_KEY = 'sb_publishable_AEFkZ-UQ9StkZW2zH-nOFA_Sz4AcGlS';

// ─────────────────────────────────────────────────────────────
//  WORLD & PLAYER CONSTANTS
// ─────────────────────────────────────────────────────────────
const TILE        = 32;    // base tile size in pixels
const GRAVITY     = 700;   // world gravity (px/s²)
const SPEED       = 190;   // horizontal player speed
const JUMP_VEL    = -480;  // initial jump velocity (negative = up)

// Extra per-body gravity applied in specific situations:
const FALL_GRAVITY = 600;  // player is falling → snappier landing
const CUT_GRAVITY  = 900;  // jump key released early → shorter hop

const FRAGMENTS_TO_WIN = 5;   // collect this many fragments to unlock exit
const STOMP_BOUNCE     = -280; // upward bounce velocity after stomping an enemy

const GAME_W  = 800;
const GAME_H  = 480;
const WORLD_W = 3200;

// ─────────────────────────────────────────────────────────────
//  LEVEL CONFIGURATIONS
//  Edit startBg / endObj / unlockMsg / gaps / platforms /
//  enemies / fragments / coins per level.
//
//  startBg  – image shown flush-left at world start
//             { key, srcW, srcH, displayH }
//  endObj   – physics sprite at world end (the "exit door")
//             { key, srcW, srcH, displayH }
//  unlockMsg – text shown when all fragments collected
// ─────────────────────────────────────────────────────────────
const _H = GAME_H, _T = TILE;   // shorthands used in level data

const LEVEL_CONFIGS = [

  // ══════════════════════════════════════════════════════════
  //  LEVEL 1  –  Normal  (pračka → vlak)
  // ══════════════════════════════════════════════════════════
  {
    startBg:   { key: 'washing-machine', srcW: 768,  srcH: 715,  displayH: 256 },
    endObj:    { key: 'train',           srcW: 1024, srcH: 850,  displayH: 192, flipX: true },
    unlockMsg: 'Path unlocked!',

    gaps: [
      [640,   768],
      [1280, 1408],
      [1920, 2016],
      [2528, 2656],
    ],

    platforms: [
      [300,  _H-_T*5, 3, 'platform'],
      [450,  _H-_T*3, 4, 'platform'],
      [780,  _H-_T*4, 3, 'platform'],
      [950,  _H-_T*6, 3, 'platform'],
      [1080, _H-_T*4, 3, 'brick'],
      [1200, _H-_T*3, 3, 'platform'],
      [1420, _H-_T*3, 4, 'platform'],
      [1570, _H-_T*7, 3, 'platform'],
      [1700, _H-_T*5, 3, 'brick'],
      [1820, _H-_T*3, 3, 'platform'],
      [2020, _H-_T*4, 3, 'platform'],
      [2200, _H-_T*6, 3, 'platform'],
      [2340, _H-_T*8, 3, 'brick'],
      [2460, _H-_T*5, 3, 'platform'],
      [2660, _H-_T*3, 3, 'platform'],
      [2820, _H-_T*6, 3, 'brick'],
      [2940, _H-_T*4, 3, 'platform'],
    ],

    enemies: [
      [200,  _H-_T*2], [560,  _H-_T*2], [1160, _H-_T*2], [2120, _H-_T*2],
      [315,  _H-_T*6], [470,  _H-_T*4],
      [800,  _H-_T*5], [960,  _H-_T*7], [1090, _H-_T*5],
      [1450, _H-_T*4], [1585, _H-_T*8], [1715, _H-_T*6],
      [2040, _H-_T*5], [2215, _H-_T*7], [2355, _H-_T*9],
      [2675, _H-_T*4], [2835, _H-_T*7],
    ],

    fragments: [
      [340,  _H-_T*8],
      [985,  _H-_T*8],
      [1605, _H-_T*9],
      [2375, _H-_T*10],
      [2858, _H-_T*8],
    ],

    coins: [
      [498,  _H-_T*5], [530,  _H-_T*5],
      [796,  _H-_T*6], [828,  _H-_T*6],
      [1160, _H-_T*6],
      [900,  _H-_T*2], [932,  _H-_T*2], [964,  _H-_T*2],
      [1436, _H-_T*5], [1468, _H-_T*5], [1500, _H-_T*5],
      [1836, _H-_T*5], [1868, _H-_T*5],
      [2036, _H-_T*6], [2068, _H-_T*6],
      [2216, _H-_T*8],
      [2676, _H-_T*5],
    ],
  },

  // ══════════════════════════════════════════════════════════
  //  LEVEL 2  –  Harder  (vlak → brána)
  //  Wider gaps, narrower platforms, more enemies
  // ══════════════════════════════════════════════════════════
  {
    startBg:   { key: 'train', srcW: 1024, srcH: 850,  displayH: 192 },
    endObj:    { key: 'exit',  srcW: 634,  srcH: 903,  displayH: 256 },
    unlockMsg: 'Path unlocked!',

    gaps: [
      [600,   768],   // 168 px
      [1280, 1440],   // 160 px
      [1900, 2048],   // 148 px
      [2510, 2688],   // 178 px
    ],

    platforms: [
      [280,  _H-_T*6, 3, 'platform'],
      [440,  _H-_T*4, 3, 'platform'],
      [790,  _H-_T*5, 3, 'platform'],
      [940,  _H-_T*7, 3, 'platform'],
      [1075, _H-_T*5, 3, 'brick'],
      [1210, _H-_T*3, 3, 'platform'],
      [1460, _H-_T*4, 3, 'platform'],
      [1600, _H-_T*8, 3, 'platform'],
      [1730, _H-_T*5, 3, 'brick'],
      [1840, _H-_T*3, 3, 'platform'],
      [2060, _H-_T*5, 3, 'platform'],
      [2210, _H-_T*7, 3, 'platform'],
      [2350, _H-_T*9, 3, 'brick'],
      [2470, _H-_T*5, 3, 'platform'],
      [2700, _H-_T*4, 3, 'platform'],
      [2840, _H-_T*7, 3, 'brick'],
      [2960, _H-_T*5, 3, 'platform'],
    ],

    enemies: [
      [170,  _H-_T*2], [520,  _H-_T*2], [1140, _H-_T*2], [2080, _H-_T*2], [1360, _H-_T*2],
      [290,  _H-_T*7], [455,  _H-_T*5],
      [800,  _H-_T*6], [955,  _H-_T*8], [1085, _H-_T*6],
      [1470, _H-_T*5], [1615, _H-_T*9], [1740, _H-_T*6],
      [2070, _H-_T*6], [2225, _H-_T*8], [2365, _H-_T*10],
      [2710, _H-_T*5], [2855, _H-_T*8],
    ],

    fragments: [
      [325,  _H-_T*9],
      [975,  _H-_T*9],
      [1635, _H-_T*10],
      [2385, _H-_T*11],
      [2865, _H-_T*9],
    ],

    coins: [
      [296,  _H-_T*7], [328,  _H-_T*7],
      [456,  _H-_T*5], [488,  _H-_T*5],
      [806,  _H-_T*6], [838,  _H-_T*6],
      [1091, _H-_T*6],
      [880,  _H-_T*2], [912,  _H-_T*2],
      [1476, _H-_T*5], [1508, _H-_T*5],
      [1856, _H-_T*4],
      [2076, _H-_T*6], [2108, _H-_T*6],
      [2226, _H-_T*10],
      [2716, _H-_T*5],
    ],
  },

  // ══════════════════════════════════════════════════════════
  //  LEVEL 3  –  Hardest  (brána → Final Bosu)
  //  Single-tile platforms, biggest gaps
  // ══════════════════════════════════════════════════════════
  {
    startBg:   { key: 'exit',      srcW: 634, srcH: 903,  displayH: 256 },
    endObj:    { key: 'finalbosu', srcW: 942, srcH: 696,  displayH: 360 },
    unlockMsg: 'Path unlocked!\nFinal Bosu is coming!',

    gaps: [
      [560,   768],   // 208 px
      [1260, 1472],   // 212 px
      [1880, 2096],   // 216 px
      [2496, 2720],   // 224 px
    ],

    platforms: [
      // Sec 1
      [240,  _H-_T*7, 3, 'platform'],
      [375,  _H-_T*5, 3, 'platform'],
      // Sec 2
      [800,  _H-_T*6, 3, 'platform'],
      [920,  _H-_T*8, 3, 'platform'],
      [1055, _H-_T*5, 3, 'brick'],
      [1195, _H-_T*3, 3, 'platform'],
      // Sec 3
      [1495, _H-_T*5, 3, 'platform'],
      [1615, _H-_T*9, 3, 'platform'],
      [1740, _H-_T*6, 3, 'brick'],
      [1856, _H-_T*4, 3, 'platform'],
      // Sec 4
      [2112, _H-_T*5, 3, 'platform'],
      [2240, _H-_T*8, 3, 'platform'],
      [2368, _H-_T*10, 3, 'brick'],
      [2496, _H-_T*6, 3, 'platform'],  // stepping stone over gap 4
      // Sec 5
      [2752, _H-_T*5, 3, 'platform'],
      [2880, _H-_T*8, 3, 'brick'],
      [3000, _H-_T*5, 3, 'platform'],
    ],

    enemies: [
      [140,  _H-_T*2], [480,  _H-_T*2], [1120, _H-_T*2], [2080, _H-_T*2], [1340, _H-_T*2],
      [245,  _H-_T*8], [385,  _H-_T*6],
      [805,  _H-_T*7], [925,  _H-_T*9],
      [1060, _H-_T*6], [1200, _H-_T*4],
      [1500, _H-_T*6], [1620, _H-_T*10], [1745, _H-_T*7],
      [2117, _H-_T*6], [2245, _H-_T*9],  [2373, _H-_T*11],
      [2757, _H-_T*6], [2885, _H-_T*9],
    ],

    fragments: [
      [310,  _H-_T*10],
      [960,  _H-_T*10],
      [1650, _H-_T*11],
      [2400, _H-_T*12],
      [2905, _H-_T*10],
    ],

    coins: [
      [405,  _H-_T*9], [437,  _H-_T*9],
      [391,  _H-_T*6],
      [820,  _H-_T*7],
      [840,  _H-_T*2], [872,  _H-_T*2],
      [1071, _H-_T*6],
      [1511, _H-_T*6], [1543, _H-_T*6],
      [1872, _H-_T*5],
      [2128, _H-_T*6],
      [2256, _H-_T*9],
      [2768, _H-_T*6],
    ],
  },

];

// ─────────────────────────────────────────────────────────────
//  TITLE SCENE  –  Final Bosu brand × Keshuma game aesthetic
//
//  Palette blend:
//    FB yellow   #F0E800  – logo, headings, button border
//    FB magenta  #E51A4B  – logo stroke, accents, button bg
//    KB midnight #0F0C1E  – base dark (game sky)
//    KB lavender #CCAAFF  – subtitle, body text tint
//
//  Font: Orbitron 900 (bold geometric – closest free match to
//        Akira Expanded used on finalbosu.com).
//        Loaded via Google Fonts in index.html.
// ─────────────────────────────────────────────────────────────
class TitleScene extends Phaser.Scene {
  constructor() { super('TitleScene'); }

  create() {
    const CX = GAME_W / 2;
    const FB_YELLOW  = '#F0E800';
    const FB_MAGENTA = '#E51A4B';
    const KB_LAVENDER = '#CCAAFF';
    const FONT_BRAND  = "'Orbitron', monospace";
    const FONT_BODY   = 'monospace';

    // ── Background: Keshuma sky + deep overlay ───────────────
    this.add.tileSprite(0, 0, GAME_W, GAME_H, 'sky').setOrigin(0, 0);
    this.add.rectangle(0, 0, GAME_W, GAME_H, 0x000000, 0.55).setOrigin(0, 0);

    // ── Magenta glow halo behind the title ───────────────────
    const glow = this.add.graphics();
    glow.fillStyle(0xE51A4B, 0.07);
    glow.fillEllipse(CX, 72, 640, 130);
    glow.fillStyle(0xE51A4B, 0.04);
    glow.fillEllipse(CX, 72, 780, 160);

    // ── Logo: use logo.png if loaded, otherwise fall back to styled text ──
    const logoTex = this.textures.get('logo');
    if (logoTex && logoTex.source[0].width > 4) {
      const srcW = logoTex.source[0].width;
      const srcH = logoTex.source[0].height;
      const dH   = 130;
      const dW   = Math.round(srcW * (dH / srcH));
      this.add.image(CX, 12, 'logo').setOrigin(0.5, 0).setDisplaySize(dW, dH);
    } else {
      // Shadow layer (offset, magenta)
      this.add.text(CX + 3, 27, 'FINAL', {
        fontSize: '54px', fill: FB_MAGENTA, fontFamily: FONT_BRAND, fontStyle: 'bold'
      }).setOrigin(0.5, 0).setAlpha(0.55);
      this.add.text(CX + 3, 78, 'BOSU', {
        fontSize: '64px', fill: FB_MAGENTA, fontFamily: FONT_BRAND, fontStyle: 'bold'
      }).setOrigin(0.5, 0).setAlpha(0.55);
      // Main layer (yellow fill, magenta stroke)
      this.add.text(CX, 24, 'FINAL', {
        fontSize: '54px', fill: FB_YELLOW, fontFamily: FONT_BRAND, fontStyle: 'bold',
        stroke: FB_MAGENTA, strokeThickness: 4
      }).setOrigin(0.5, 0);
      this.add.text(CX, 75, 'BOSU', {
        fontSize: '64px', fill: FB_YELLOW, fontFamily: FONT_BRAND, fontStyle: 'bold',
        stroke: FB_MAGENTA, strokeThickness: 5
      }).setOrigin(0.5, 0);
    }

    // ── Subtitle ──────────────────────────────────────────────
    this.add.text(CX, 150, 'THE  PATH  OF  THE  MUJIN', {
      fontSize: '13px', fill: KB_LAVENDER, fontFamily: FONT_BRAND,
      stroke: '#000', strokeThickness: 2,
      letterSpacing: 6
    }).setOrigin(0.5, 0);

    // ── Divider: magenta tinted line ──────────────────────────
    const divY = 178;
    const g = this.add.graphics();
    g.lineStyle(1, 0xE51A4B, 0.5);
    g.lineBetween(60, divY, GAME_W - 60, divY);
    // small diamond accent
    g.fillStyle(0xE51A4B, 0.7);
    g.fillRect(CX - 4, divY - 3, 8, 6);

    // ── HOW TO PLAY ───────────────────────────────────────────
    const howY = divY + 12;
    this.add.text(CX, howY, 'HOW  TO  PLAY', {
      fontSize: '11px', fill: FB_YELLOW, fontFamily: FONT_BRAND,
      stroke: '#000', strokeThickness: 2, letterSpacing: 4
    }).setOrigin(0.5, 0);

    // Two-column layout: controls left, objectives right
    const col1 = 90, col2 = CX + 30;
    const rowH = 17, startY = howY + 22;

    const left = [
      ['CONTROLS', FB_YELLOW, true],
      ['← → / A D    Move', '#DDDDDD', false],
      ['↑ W SPACE    Jump', '#DDDDDD', false],
      ['', '', false],
      ['release early = short hop', '#888888', false],
    ];
    const right = [
      ['OBJECTIVES', FB_YELLOW, true],
      ['★ Collect 5 Fragments', FB_YELLOW, false],
      ['  → unlocks the exit', '#AAAAAA', false],
      ['⚔ Stomp Kaichukan  +200', FB_MAGENTA, false],
      ['● Grab Coins  +100', '#FFD700', false],
    ];

    left.forEach(([txt, color, bold], i) => {
      this.add.text(col1, startY + i * rowH, txt, {
        fontSize: bold ? '11px' : '11px',
        fill: color, fontFamily: bold ? FONT_BRAND : FONT_BODY,
        stroke: '#000', strokeThickness: bold ? 2 : 1,
        fontStyle: bold ? 'bold' : 'normal'
      }).setOrigin(0, 0);
    });
    right.forEach(([txt, color, bold], i) => {
      this.add.text(col2, startY + i * rowH, txt, {
        fontSize: '11px', fill: color,
        fontFamily: bold ? FONT_BRAND : FONT_BODY,
        stroke: '#000', strokeThickness: bold ? 2 : 1,
        fontStyle: bold ? 'bold' : 'normal'
      }).setOrigin(0, 0);
    });

    // ── 3-level info strip ────────────────────────────────────
    const stripY = startY + left.length * rowH + 10;
    this.add.rectangle(CX, stripY + 10, GAME_W - 80, 22, 0xE51A4B, 0.12).setOrigin(0.5, 0.5);
    this.add.text(CX, stripY + 2, '3 LEVELS  ·  METORA  →  TRAIN  →  GATE  →  FINAL BOSU', {
      fontSize: '9px', fill: KB_LAVENDER, fontFamily: FONT_BODY,
      stroke: '#000', strokeThickness: 1
    }).setOrigin(0.5, 0);

    // ── START GAME button ─────────────────────────────────────
    const btnY = GAME_H - 46;

    // Button background rect (drawn separately for clean look)
    const btnBg = this.add.rectangle(CX, btnY, 240, 38, 0xE51A4B, 1)
      .setOrigin(0.5, 0.5)
      .setInteractive({ useHandCursor: true });
    // Yellow border – Rectangle with origin 0.5 so it pulses from centre
    const btnBorder = this.add.rectangle(CX, btnY, 244, 42, 0x000000, 0)
      .setOrigin(0.5, 0.5)
      .setStrokeStyle(2, 0xF0E800);
    // Button text
    const btnTxt = this.add.text(CX, btnY, '▶  START GAME', {
      fontSize: '18px', fill: '#FFFFFF', fontFamily: FONT_BRAND, fontStyle: 'bold',
      stroke: '#000', strokeThickness: 2
    }).setOrigin(0.5, 0.5);

    // Pulse animation on text + bg together
    this.tweens.add({
      targets: [btnBg, btnTxt, btnBorder],
      scaleX: 1.03, scaleY: 1.03,
      duration: 650, ease: 'Sine.easeInOut', yoyo: true, repeat: -1
    });

    btnBg.on('pointerover',  () => { btnBg.setFillStyle(0xFF2255); btnTxt.setStyle({ fill: FB_YELLOW }); });
    btnBg.on('pointerout',   () => { btnBg.setFillStyle(0xE51A4B); btnTxt.setStyle({ fill: '#FFFFFF' }); });
    btnBg.on('pointerdown',  () => this.startGame());

    this.input.keyboard.on('keydown-SPACE', () => this.startGame());
    this.input.keyboard.on('keydown-ENTER', () => this.startGame());
  }

  startGame() {
    this.registry.set('currentLevel', 0);
    this.scene.stop('TitleScene');
    this.scene.start('GameScene');
    this.scene.start('UIScene');
    this.scene.bringToTop('UIScene');
  }
}

// ─────────────────────────────────────────────────────────────
//  BOOT SCENE  –  procedural placeholder graphics
// ─────────────────────────────────────────────────────────────
class BootScene extends Phaser.Scene {
  constructor() { super('BootScene'); }

  preload() {
    // ── WORLD TILES (Keshuma-inspired: ancient stone & desert) ──

    // [BACKGROUND GRAPHICS] ───────────────────────────────────
    // Replace with: this.load.image('sky', 'assets/sky.png');
    // Then in GameScene.create() swap tileSprite key to 'sky'.
    this.makeKeshumaSky('sky', GAME_W, GAME_H);

    // Ground – sandy desert stone
    this.makeGroundTile('ground');

    // Platform – pale lavender-grey ancient stone (castle walls)
    this.makePlatformTile('platform');

    // Brick – warmer rose-lavender carved stone variant
    this.makeBrickTile('brick');

    // [PLAYER GRAPHICS] ───────────────────────────────────────
    this.load.spritesheet('player', 'assets/player_walk.png',
      { frameWidth: 628, frameHeight: 950 });

    // [ENEMY GRAPHICS] ────────────────────────────────────────
    this.load.spritesheet('enemy', 'assets/enemy_walk.png',
      { frameWidth: 617, frameHeight: 753 });

    // [COIN GRAPHICS] ─────────────────────────────────────────
    // Replace with: this.load.image('coin', 'assets/coin.png');
    this.makeCircle('coin',   16,   0xFFD700);

    // [FRAGMENT GRAPHICS] ─────────────────────────────────────
    // Fragments are the KEY items – collect all 5 to unlock exit.
    this.load.image('fragment', 'assets/fragment.png');

    // [EXIT GRAPHICS] ─────────────────────────────────────────
    this.load.image('exit', 'assets/gate.png');

    // [LEVEL BACKGROUND / START-END IMAGES] ───────────────────
    this.load.image('washing-machine', 'assets/washing-machine.png');
    this.load.image('train',           'assets/train.png');
    this.load.image('finalbosu',       'assets/finalbosu.png');

    // [TITLE SCREEN LOGO] ─────────────────────────────────────
    // Drop assets/logo.png (the Final Bosu logo) to show it on the title screen.
    // If the file is missing the title screen falls back to styled text.
    this.load.image('logo', 'assets/logo.png');

    // [AUDIO] ─────────────────────────────────────────────────
    this.load.audio('music',       'assets/main_loop.ogg');
    this.load.audio('sfx_jump',    'assets/jump.wav');
    this.load.audio('sfx_coin',    'assets/coin.wav');
    this.load.audio('sfx_clear',   'assets/level_clear.wav');
  }

  create() {
    // Kick off font load in background; poll every frame until ready (max 60 frames)
    let waited = 0;
    const tryLaunch = () => {
      waited++;
      const ready = !document.fonts.load ||
        document.fonts.check("900 16px 'Orbitron'") || waited > 60;
      if (ready) {
        this.scene.start('TitleScene');
      } else {
        this.time.delayedCall(16, tryLaunch);
      }
    };
    // Trigger the browser to start loading the font
    if (document.fonts && document.fonts.load) {
      document.fonts.load("900 16px 'Orbitron'");
    }
    tryLaunch();
  }

  // ── TEXTURE GENERATORS ──────────────────────────────────────

  makeRect(key, w, h, color) {
    if (this.textures.exists(key)) return;
    const g = this.make.graphics({ x: 0, y: 0, add: false });
    g.fillStyle(color, 1);
    g.fillRect(0, 0, w, h);
    g.lineStyle(1, 0x000000, 0.3);
    g.strokeRect(0, 0, w, h);
    g.generateTexture(key, w, h);
    g.destroy();
  }

  makeCircle(key, r, color) {
    if (this.textures.exists(key)) return;
    const size = r * 2;
    const g = this.make.graphics({ x: 0, y: 0, add: false });
    g.fillStyle(color, 1);
    g.fillCircle(r, r, r - 1);
    g.lineStyle(1.5, 0xB8860B, 1);
    g.strokeCircle(r, r, r - 1);
    g.generateTexture(key, size, size);
    g.destroy();
  }

  makeStar(key, r, color) {
    if (this.textures.exists(key)) return;
    const size = r * 2 + 2;
    const cx = size / 2, cy = size / 2;
    const pts = [];
    for (let i = 0; i < 10; i++) {
      const angle  = (i * Math.PI) / 5 - Math.PI / 2;
      const radius = i % 2 === 0 ? r : r * 0.4;
      pts.push({ x: cx + radius * Math.cos(angle), y: cy + radius * Math.sin(angle) });
    }
    const g = this.make.graphics({ x: 0, y: 0, add: false });
    g.fillStyle(color, 1);
    g.fillPoints(pts, true);
    g.lineStyle(1, 0xE65100, 1);
    g.strokePoints(pts, true);
    g.generateTexture(key, size, size);
    g.destroy();
  }

  makeBg(key, w, h, colorTop, colorBot) {
    if (this.textures.exists(key)) return;
    const g = this.make.graphics({ x: 0, y: 0, add: false });
    const steps = 20;
    for (let i = 0; i < steps; i++) {
      const r = Phaser.Display.Color.Interpolate.ColorWithColor(
        Phaser.Display.Color.ValueToColor(colorTop),
        Phaser.Display.Color.ValueToColor(colorBot), steps, i);
      g.fillStyle(Phaser.Display.Color.GetColor(r.r, r.g, r.b), 1);
      g.fillRect(0, Math.floor(i * h / steps), w, Math.ceil(h / steps) + 1);
    }
    g.generateTexture(key, w, h);
    g.destroy();
  }

  makeExit(key, w, h, color) {
    if (this.textures.exists(key)) return;
    const g = this.make.graphics({ x: 0, y: 0, add: false });
    g.fillStyle(0x555555, 1);
    g.fillRect(0, 0, w, h);
    g.fillStyle(color, 1);
    g.fillRect(3, 3, w - 6, h - 3);
    g.fillStyle(0xFFD700, 1);
    g.fillCircle(w - 7, h / 2, 3);
    g.generateTexture(key, w, h);
    g.destroy();
  }

  // ── KESHUMA TEXTURE GENERATORS ──────────────────────────────

  /**
   * makeKeshumaSky – 4-stop vertical gradient:
   *   top    0x0F0C1E  deep midnight
   *   35%    0x3D3268  deep purple
   *   70%    0x7A6898  dusty lavender
   *   bottom 0xC8B08A  warm sandy ochre
   */
  makeKeshumaSky(key, w, h) {
    if (this.textures.exists(key)) return;
    const g = this.make.graphics({ x: 0, y: 0, add: false });
    // stops: [t, r, g, b]
    const stops = [
      [0.00, 0x0F, 0x0C, 0x1E],
      [0.35, 0x3D, 0x32, 0x68],
      [0.70, 0x7A, 0x68, 0x98],
      [1.00, 0xC8, 0xB0, 0x8A],
    ];
    const rows = 96;
    for (let i = 0; i < rows; i++) {
      const t = i / (rows - 1);
      // find surrounding stops
      let s0 = stops[0], s1 = stops[1];
      for (let j = 0; j < stops.length - 1; j++) {
        if (t >= stops[j][0] && t <= stops[j + 1][0]) { s0 = stops[j]; s1 = stops[j + 1]; }
      }
      const lt = (s1[0] - s0[0]) < 0.0001 ? 0 : (t - s0[0]) / (s1[0] - s0[0]);
      const rr = Math.round(s0[1] + (s1[1] - s0[1]) * lt);
      const gg = Math.round(s0[2] + (s1[2] - s0[2]) * lt);
      const bb = Math.round(s0[3] + (s1[3] - s0[3]) * lt);
      g.fillStyle((rr << 16) | (gg << 8) | bb, 1);
      const y0 = Math.floor(i * h / rows);
      g.fillRect(0, y0, w, Math.ceil(h / rows) + 1);
    }
    g.generateTexture(key, w, h);
    g.destroy();
  }

  /**
   * makeGroundTile – sandy desert stone (32×32)
   *   face    0xA08455  ochre sand-stone
   *   top     0xC4A870  sunlit highlight
   *   bottom  0x705838  deep shadow
   */
  makeGroundTile(key) {
    if (this.textures.exists(key)) return;
    const T = TILE;
    const g = this.make.graphics({ x: 0, y: 0, add: false });
    // Main face
    g.fillStyle(0xA08455, 1);
    g.fillRect(0, 0, T, T);
    // Sunlit top strip
    g.fillStyle(0xC4A870, 1);
    g.fillRect(0, 0, T, 5);
    // Shadow bottom strip
    g.fillStyle(0x705838, 1);
    g.fillRect(0, T - 4, T, 4);
    // Subtle vertical crack
    g.lineStyle(1, 0x705838, 0.40);
    g.lineBetween(T * 0.5, 5, T * 0.5, T - 4);
    // Horizontal dust band
    g.lineStyle(1, 0xC4A870, 0.25);
    g.lineBetween(2, T * 0.55, T - 2, T * 0.55);
    // Outer border
    g.lineStyle(1, 0x4A3820, 0.65);
    g.strokeRect(0, 0, T, T);
    g.generateTexture(key, T, T);
    g.destroy();
  }

  /**
   * makePlatformTile – pale lavender-grey ancient castle stone (32×32)
   *   face    0x7A6898  dusty lavender stone
   *   top     0x9E8EC0  light-catching edge
   *   bottom  0x4E3E70  deep shadow
   */
  makePlatformTile(key) {
    if (this.textures.exists(key)) return;
    const T = TILE;
    const g = this.make.graphics({ x: 0, y: 0, add: false });
    // Main face
    g.fillStyle(0x7A6898, 1);
    g.fillRect(0, 0, T, T);
    // Top highlight
    g.fillStyle(0x9E8EC0, 1);
    g.fillRect(0, 0, T, 5);
    // Bottom shadow
    g.fillStyle(0x4E3E70, 1);
    g.fillRect(0, T - 5, T, 5);
    // Stone groove lines (horizontal chisel marks)
    g.lineStyle(1, 0x4E3E70, 0.30);
    g.lineBetween(2, T * 0.40, T - 2, T * 0.40);
    g.lineBetween(2, T * 0.72, T - 2, T * 0.72);
    // Vertical joint
    g.lineStyle(1, 0x9E8EC0, 0.20);
    g.lineBetween(T * 0.5, 5, T * 0.5, T - 5);
    // Outer border
    g.lineStyle(1, 0x2E1E50, 0.70);
    g.strokeRect(0, 0, T, T);
    g.generateTexture(key, T, T);
    g.destroy();
  }

  /**
   * makeBrickTile – rose-lavender carved stone variant (32×32)
   *   face    0x886078  warm rose-grey
   *   top     0xAA8098  highlight
   *   bottom  0x604050  shadow
   *   mortar lines give a proper brick feel
   */
  makeBrickTile(key) {
    if (this.textures.exists(key)) return;
    const T = TILE;
    const g = this.make.graphics({ x: 0, y: 0, add: false });
    // Main face
    g.fillStyle(0x886078, 1);
    g.fillRect(0, 0, T, T);
    // Top highlight
    g.fillStyle(0xAA8098, 1);
    g.fillRect(0, 0, T, 4);
    // Bottom shadow
    g.fillStyle(0x604050, 1);
    g.fillRect(0, T - 4, T, 4);
    // Mortar lines – brick pattern offset by half
    g.lineStyle(1, 0x604050, 0.60);
    g.lineBetween(0, T / 2, T, T / 2);         // horizontal centre
    g.lineBetween(T * 0.25, 4, T * 0.25, T / 2); // top row left joint
    g.lineBetween(T * 0.75, 4, T * 0.75, T / 2); // top row right joint
    g.lineBetween(T * 0.5,  T / 2, T * 0.5, T - 4); // bottom row centre joint
    // Outer border
    g.lineStyle(1, 0x3A2030, 0.70);
    g.strokeRect(0, 0, T, T);
    g.generateTexture(key, T, T);
    g.destroy();
  }

  /**
   * makeWashingMachine – giant front-loading portal machine (400×280 px)
   *
   *  Palette matches Keshuma:
   *    body    0x14102A  deep midnight shell
   *    outline 0xC0A0D8  lavender-rose edges
   *    drum    0xC88008  amber portal glow  ← where people respawn
   *    goo     0xB87008  amber drip below door
   *    people  0x0E0618  dark silhouettes tumbling inside
   *
   *  Layout (left → right):
   *    [ control panel | drum opening (glowing) | right porthole + vents ]
   *    goo stream + drip blobs pour from the drum bottom
   *    top intake pipe sits above the machine body
   */
  makeWashingMachine(key, w, h) {
    if (this.textures.exists(key)) return;
    const g = this.make.graphics({ x: 0, y: 0, add: false });

    const bx = 8, by = 25, bw = 384, bh = 225;
    const OL = 0xC0A0D8;  // lavender-rose outline

    // ── drop shadow ───────────────────────────────────────────
    g.fillStyle(0x06030E, 0.50);
    g.fillRect(bx + 7, by + 7, bw, bh);

    // ── main body ─────────────────────────────────────────────
    g.fillStyle(0x14102A, 1);
    g.fillRect(bx, by, bw, bh);
    // top sheen
    g.fillStyle(0x281848, 0.50);
    g.fillRect(bx + 1, by + 1, bw - 2, 28);

    // ── left control panel ────────────────────────────────────
    const lpx = bx + 8, lpy = by + 12, lpw = 68, lph = bh - 24;
    g.fillStyle(0x0E0820, 1);
    g.fillRect(lpx, lpy, lpw, lph);
    g.lineStyle(1.5, OL, 0.48);
    g.strokeRect(lpx, lpy, lpw, lph);

    // button cluster box
    g.fillStyle(0x1C1038, 1);
    g.fillRect(lpx + 5, lpy + 7, lpw - 10, 34);
    g.lineStyle(1, OL, 0.32);
    g.strokeRect(lpx + 5, lpy + 7, lpw - 10, 34);
    // rectangular buttons
    g.fillStyle(0xB0A0CC, 1);
    g.fillRect(lpx + 9, lpy + 13, 22, 7);
    g.fillRect(lpx + 9, lpy + 24, 22, 7);
    // LED indicators
    g.fillStyle(0xFFCC00, 1); g.fillCircle(lpx + 44, lpy + 16, 5);
    g.fillStyle(0xCC40BB, 1); g.fillCircle(lpx + 44, lpy + 27, 5);

    // vent grill
    g.lineStyle(1.5, OL, 0.28);
    for (let i = 0; i < 6; i++) {
      g.lineBetween(lpx + 5, lpy + 52 + i * 12, lpx + lpw - 5, lpy + 52 + i * 12);
    }

    // rotary dial
    const dx = lpx + lpw / 2, dy = lpy + lph - 27;
    g.fillStyle(0x201440, 1); g.fillCircle(dx, dy, 19);
    g.lineStyle(1.5, OL, 0.58); g.strokeCircle(dx, dy, 19);
    g.lineStyle(2, 0xFFCC00, 0.72); g.strokeCircle(dx, dy, 11);
    g.lineBetween(dx, dy - 19, dx, dy - 11);   // tick marker

    // ── drum (open door, portal glow) ─────────────────────────
    const cx = bx + Math.round(bw * 0.53);  // ≈ 211
    const cy = by + Math.round(bh / 2);     // ≈ 137
    const ro = Math.round(bh * 0.37);       // ≈ 83

    // outer frame ring
    g.fillStyle(0x1A1040, 1);
    g.fillCircle(cx, cy, ro + 12);
    g.lineStyle(3, OL, 0.88);
    g.strokeCircle(cx, cy, ro + 12);

    // amber interior – layered glow
    g.fillStyle(0xC88008, 1);
    g.fillCircle(cx, cy, ro);
    g.fillStyle(0xECA820, 0.60);
    g.fillCircle(cx, cy, Math.round(ro * 0.73));
    g.fillStyle(0xFFE870, 0.28);
    g.fillCircle(cx, cy, Math.round(ro * 0.44));

    // concentric drum rings
    g.lineStyle(2, 0x785008, 0.58);
    g.strokeCircle(cx, cy, ro - 1);
    g.strokeCircle(cx, cy, Math.round(ro * 0.76));
    g.strokeCircle(cx, cy, Math.round(ro * 0.52));
    g.strokeCircle(cx, cy, Math.round(ro * 0.28));

    // ── goo stream ────────────────────────────────────────────
    const gtY = cy + ro - 8;   // where goo exits the drum
    const gbY = by + bh;       // machine bottom edge
    const ghw = 24;            // half-width at top of stream

    g.fillStyle(0xB87008, 0.92);
    g.fillPoints([
      { x: cx - ghw,       y: gtY },
      { x: cx + ghw,       y: gtY },
      { x: cx + ghw + 10,  y: gbY },
      { x: cx - ghw - 10,  y: gbY },
    ], true);

    // drip blobs below the machine body
    g.fillStyle(0xA66206, 0.90);
    g.fillEllipse(cx, gbY + 14, 52, 22);
    g.fillCircle(cx - 18, gbY + 26, 8);
    g.fillCircle(cx + 16, gbY + 24, 7);
    g.fillCircle(cx + 4,  gbY + 22, 5);

    // ── people silhouettes tumbling inside ────────────────────
    g.fillStyle(0x0E0618, 0.90);

    // person A – arms spread, falling
    const ax = cx - 25, ay = cy - 20;
    g.fillCircle(ax, ay, 7);
    g.fillRect(ax - 3, ay + 7, 6, 13);
    g.fillRect(ax - 15, ay + 9, 13, 4);
    g.fillRect(ax + 3,  ay + 9, 13, 4);
    g.fillRect(ax - 5,  ay + 20, 5, 11);
    g.fillRect(ax + 1,  ay + 20, 5, 11);

    // person B – crouched at drum bottom
    const bqx = cx + 22, bqy = cy + Math.round(ro * 0.47);
    g.fillCircle(bqx, bqy - 7, 6);
    g.fillRect(bqx - 4, bqy - 1, 8, 10);
    g.fillRect(bqx - 6, bqy + 9, 5, 7);
    g.fillRect(bqx + 2, bqy + 9, 5, 7);

    // person C – halfway into the goo stream
    g.fillCircle(cx - 3, gtY + 10, 5);
    g.fillRect(cx - 6, gtY + 15, 6, 8);

    // ── right porthole ────────────────────────────────────────
    const pox = bx + bw - 52, poy = by + 50;
    g.fillStyle(0x18103A, 1); g.fillCircle(pox, poy, 31);
    g.lineStyle(2, OL, 0.72); g.strokeCircle(pox, poy, 31);
    g.fillStyle(0xC88008, 0.78); g.fillCircle(pox, poy, 22);
    g.lineStyle(1.5, 0x785008, 0.52);
    g.strokeCircle(pox, poy, 22);
    g.strokeCircle(pox, poy, 11);
    // porthole hinge
    g.fillStyle(0x302060, 1); g.fillRect(pox + 27, poy - 5, 14, 10);
    g.lineStyle(1, OL, 0.45); g.strokeRect(pox + 27, poy - 5, 14, 10);

    // ── right vent stripes ────────────────────────────────────
    const vx0 = cx + ro + 18, vx1 = bx + bw - 12;
    if (vx1 > vx0 + 8) {
      g.lineStyle(1.5, OL, 0.22);
      for (let i = 0; i < 5; i++) {
        g.lineBetween(vx0, by + Math.round(bh * 0.54) + i * 17,
                      vx1, by + Math.round(bh * 0.54) + i * 17);
      }
    }

    // ── top intake pipe ───────────────────────────────────────
    const pipX = cx - 18;
    g.fillStyle(0x1A1038, 1); g.fillRect(pipX, by - 16, 36, 18);
    g.lineStyle(1.5, OL, 0.62); g.strokeRect(pipX, by - 16, 36, 18);
    g.fillStyle(0x241848, 1); g.fillRect(pipX + 5, by - 22, 26, 7);
    g.lineStyle(1, OL, 0.42); g.strokeRect(pipX + 5, by - 22, 26, 7);

    // ── body outline (last – crisps all edges) ────────────────
    g.lineStyle(2.5, OL, 0.86);
    g.strokeRect(bx, by, bw, bh);
    // panel divider
    g.lineStyle(1.5, OL, 0.40);
    g.lineBetween(lpx + lpw, by + 1, lpx + lpw, by + bh - 1);

    g.generateTexture(key, w, h);
    g.destroy();
  }
}

// ─────────────────────────────────────────────────────────────
//  GAME SCENE
// ─────────────────────────────────────────────────────────────
class GameScene extends Phaser.Scene {
  constructor() { super('GameScene'); }

  init() {
    // Read level from shared registry; default to 0 on first run
    if (this.registry.get('currentLevel') === undefined || this.registry.get('currentLevel') === null) {
      this.registry.set('currentLevel', 0);
    }
    this.currentLevel        = this.registry.get('currentLevel');
    this.cfg                 = LEVEL_CONFIGS[this.currentLevel];

    this.score               = 0;
    this.fragmentsCollected  = 0;
    this.exitOpen            = false;
    this.playerDead          = false;
    this.jumpKeyDown         = false;
    this.wasOnGround         = true;
  }

  create() {
    // Background music – loop forever, respect system mute
    if (!this.sound.get('music')) {
      this.sound.play('music', { loop: true, volume: 0.5 });
    }

    this.physics.world.setBounds(0, 0, WORLD_W, GAME_H);
    // Disable bottom-wall collision so the player falls into pits.
    // Left/right walls are still active (player can't scroll off-screen).
    // The handlePlayerMovement() check (p.y > GAME_H + 60) triggers death.
    this.physics.world.setBoundsCollision(true, true, false, false);

    // [BACKGROUND GRAPHICS] – swap 'sky' for your own texture key
    this.add.tileSprite(0, 0, WORLD_W, GAME_H, 'sky').setOrigin(0, 0);

    // [START BACKGROUND] – image flush-left, anchored to bottom-left.
    // Source dimensions from cfg keep aspect ratio correct.
    const sb = this.cfg.startBg;
    const sbImg = this.add.image(0, GAME_H, sb.key)
      .setOrigin(0, 1)
      .setDisplaySize(Math.round(sb.srcW * (sb.displayH / sb.srcH)), sb.displayH);
    if (sb.angle) sbImg.setAngle(sb.angle);
    if (sb.flipX) sbImg.setFlipX(true);

    this.platforms = this.physics.add.staticGroup();
    this.buildLevel();

    // [PLAYER GRAPHICS]
    this.player = this.physics.add.sprite(80, GAME_H - TILE * 2, 'player');
    this.player.setCollideWorldBounds(true);
    // Display at 48×72 screen px (preserves aspect of 628×950 source)
    this.player.setDisplaySize(48, 72);
    this.pBSX = this.player.scaleX;  // 48/628 ≈ 0.0764
    this.pBSY = this.player.scaleY;  // 72/950 ≈ 0.0758
    // Physics body: 28×66 screen px, centered in sprite
    this.player.body.setSize(28 / this.pBSX, 66 / this.pBSY);
    this.player.body.setOffset((628 - 28 / this.pBSX) / 2, (950 - 66 / this.pBSY) / 2);

    // Player animations (4-frame walk sheet)
    if (!this.anims.exists('p_idle')) {
      this.anims.create({ key: 'p_idle', frames: [{ key: 'player', frame: 0 }], frameRate: 1 });
      this.anims.create({ key: 'p_walk',
        frames: this.anims.generateFrameNumbers('player', { start: 0, end: 3 }),
        frameRate: 8, repeat: -1 });
    }
    this.player.anims.play('p_idle');

    // [ENEMY GRAPHICS]
    this.enemies = this.physics.add.group();
    this.spawnEnemies();

    // [COIN GRAPHICS]
    this.coinGroup = this.physics.add.staticGroup();
    this.spawnCoins();

    // [FRAGMENT GRAPHICS]
    this.fragments = this.physics.add.staticGroup();
    this.spawnFragments();

    // [EXIT GRAPHICS] – image taken from cfg.endObj for this level
    const eo = this.cfg.endObj;
    // Y: place sprite so its bottom rests on the ground surface (GAME_H - TILE)
    const exitDoorY = GAME_H - TILE - eo.displayH / 2;
    this.exitDoor = this.physics.add.staticSprite(WORLD_W - 80, exitDoorY, eo.key);
    this.exitDoor.setDisplaySize(
      Math.round(eo.srcW * (eo.displayH / eo.srcH)),
      eo.displayH
    );
    if (eo.angle)  this.exitDoor.setAngle(eo.angle);
    if (eo.flipX)  this.exitDoor.setFlipX(true);
    this.exitDoor.refreshBody();
    this.exitDoor.setVisible(false);
    this.exitDoor.body.enable = false;

    // Colliders
    this.physics.add.collider(this.player,  this.platforms);
    // One-way: enemies only collide with the TOP of platform tiles (not sides).
    // Phaser may pass args as (dynamic, static) or (static, dynamic), so identify
    // the enemy (dynamic physicsType=0) and tile (static physicsType=1) by type.
    this.physics.add.collider(this.enemies, this.platforms, null,
      (a, b) => {
        const [dyn, stat] = a.body.physicsType === 0 ? [a, b] : [b, a];
        return dyn.body.bottom <= stat.body.top + dyn.body.halfHeight;
      },
      this);

    this.physics.add.overlap(this.player, this.coinGroup,  this.collectCoin,        null, this);
    this.physics.add.overlap(this.player, this.fragments,  this.collectFragment,    null, this);
    this.physics.add.overlap(this.player, this.enemies,    this.handleEnemyContact, null, this);
    this.physics.add.overlap(this.player, this.exitDoor,   this.reachExit,          null, this);

    // Camera
    this.cameras.main.setBounds(0, 0, WORLD_W, GAME_H);
    this.cameras.main.startFollow(this.player, true, 0.1, 0.1);

    // Input
    this.cursors = this.input.keyboard.createCursorKeys();
    this.wasd    = this.input.keyboard.addKeys({
      up:    Phaser.Input.Keyboard.KeyCodes.W,
      left:  Phaser.Input.Keyboard.KeyCodes.A,
      right: Phaser.Input.Keyboard.KeyCodes.D
    });

    this.scene.get('UIScene').setGameScene(this);
    this.addClouds();
  }

  update() {
    if (this.playerDead) return;
    this.handlePlayerMovement();
    this.updateEnemies();
  }

  // ─────────────────────────────────────────────────────────
  //  LEVEL LAYOUT
  //
  //  Visual map (not to scale):
  //
  //  [start]──plat─plat────[GAP1]──plat──HIGH──plat──[GAP2]──
  //  ──plat──VERYHIGH──plat──[GAP3]──plat──HIGH──PEAK──plat──
  //  ──[GAP4]──plat──HIGH──plat──[GAP5]──plat─────[EXIT]
  //
  //  Gaps force precise jumps. High/peak platforms require
  //  stepping-stone sequences. Ground sections between gaps
  //  let the player recover and collect coins.
  // ─────────────────────────────────────────────────────────
  buildLevel() {
    const H = GAME_H;
    const T = TILE;

    // ── GROUND (with pits from current level config) ─────────
    for (let x = 0; x < WORLD_W; x += T) {
      const cx = x + T / 2;
      const inGap = this.cfg.gaps.some(([a, b]) => cx > a && cx < b);
      if (!inGap) {
        this.platforms.create(cx, H - T / 2, 'ground');
      }
    }

    // ── PLATFORMS from current level config ───────────────────
    this.cfg.platforms.forEach(([startX, y, len, tex]) => {
      for (let i = 0; i < len; i++) {
        this.platforms.create(startX + i * T + T / 2, y, tex);
      }
    });
  }

  // ─────────────────────────────────────────────────────────
  //  ENEMY SPAWNING  –  from level config
  // ─────────────────────────────────────────────────────────
  spawnEnemies() {
    // Create enemy walk animation once
    if (!this.anims.exists('e_walk')) {
      this.anims.create({ key: 'e_walk',
        frames: this.anims.generateFrameNumbers('enemy', { start: 0, end: 3 }),
        frameRate: 7, repeat: -1 });
    }

    this.cfg.enemies.forEach(([x, y]) => {
      // Spawn slightly above configured y so the body doesn't start
      // embedded inside the platform tile (body.bottom = y+35, tile.top = y+16 normally).
      const e = this.enemies.create(x, y - 24, 'enemy');
      // Spritesheet frame is 617×753 → at height 64px width = 52px (ratio preserved)
      e.setDisplaySize(52, 64);
      e.setCollideWorldBounds(true);
      e.setBounceX(0);
      e.setVelocityX(70);
      e.patrolDir    = 1;
      e.lastFlipTime = 0;
      e.body.setSize(44 / e.scaleX, 58 / e.scaleY);
      e.body.setOffset((617 - 44 / e.scaleX) / 2, 6);
      e.anims.play('e_walk');
    });
  }

  // ─────────────────────────────────────────────────────────
  //  COIN SPAWNING  –  from level config
  // ─────────────────────────────────────────────────────────
  spawnCoins() {
    this.cfg.coins.forEach(([x, y]) => {
      // [COIN GRAPHICS] – replace 'coin' with your own texture key
      const c = this.coinGroup.create(x, y, 'coin');
      c.body.setSize(20, 20);
      this.tweens.add({
        targets: c, y: y - 6, duration: 800,
        ease: 'Sine.easeInOut', yoyo: true, repeat: -1
      });
    });
  }

  // ─────────────────────────────────────────────────────────
  //  FRAGMENT SPAWNING  –  from level config (exactly 5)
  //  All 5 required to unlock exit.
  // ─────────────────────────────────────────────────────────
  spawnFragments() {
    this.cfg.fragments.forEach(([x, y]) => {
      // [FRAGMENT GRAPHICS] – replace 'fragment' with your own texture key
      const f = this.fragments.create(x, y, 'fragment');
      f.setDisplaySize(75, 50);   // 1536×1024 → zachovává poměr 3:2, výška = původní hvězda
      f.refreshBody();            // přepočítat static body po změně displaySize
      f.body.setSize(24, 24);
      this.tweens.add({
        targets: f, y: y - 10, duration: 900,
        ease: 'Sine.easeInOut', yoyo: true, repeat: -1
      });
    });
  }

  // ─────────────────────────────────────────────────────────
  //  PLAYER MOVEMENT  –  variable-height jump
  // ─────────────────────────────────────────────────────────
  handlePlayerMovement() {
    const p        = this.player;
    const onGround = p.body.blocked.down;
    const jumpKey  = this.cursors.up.isDown || this.cursors.space.isDown || this.wasd.up.isDown;

    // Horizontal
    if (this.cursors.left.isDown || this.wasd.left.isDown) {
      p.setVelocityX(-SPEED);
      p.setFlipX(true);
    } else if (this.cursors.right.isDown || this.wasd.right.isDown) {
      p.setVelocityX(SPEED);
      p.setFlipX(false);
    } else {
      p.setVelocityX(p.body.velocity.x * 0.78);
    }

    // Jump – fire once per key press
    if (jumpKey && onGround && !this.jumpKeyDown) {
      p.setVelocityY(JUMP_VEL);
      this.jumpKeyDown = true;
      this.sound.play('sfx_jump', { volume: 0.6 });
    }
    if (!jumpKey) { this.jumpKeyDown = false; }

    // Variable jump height via extra gravity
    if (!jumpKey && p.body.velocity.y < 0) {
      p.body.setGravityY(CUT_GRAVITY);   // early release → fast arc cut
    } else if (p.body.velocity.y > 0) {
      p.body.setGravityY(FALL_GRAVITY);  // falling → snappier descent
    } else {
      p.body.setGravityY(0);
    }

    // ── Animation + squash-stretch ────────────────────────────
    if (!onGround) {
      p.anims.play('p_idle', true);
      if (p.body.velocity.y < -80)      p.setScale(this.pBSX * 0.82, this.pBSY);
      else if (p.body.velocity.y > 80)  p.setScale(this.pBSX,        this.pBSY);
    } else if (Math.abs(p.body.velocity.x) > 25) {
      p.anims.play('p_walk', true);
      p.setScale(this.pBSX, this.pBSY);
    } else {
      p.anims.play('p_idle', true);
      p.setScale(this.pBSX, this.pBSY);
    }

    // Landing squash
    if (!this.wasOnGround && onGround && !this.playerDead) {
      this.tweens.add({
        targets: p, scaleX: this.pBSX * 1.3, scaleY: this.pBSY,
        duration: 65, ease: 'Quad.easeOut',
        yoyo: true, onComplete: () => p.setScale(this.pBSX, this.pBSY)
      });
    }
    this.wasOnGround = onGround;

    // Fell into a pit
    if (p.y > GAME_H + 60) { this.triggerPlayerDeath(); }
  }

  // ─────────────────────────────────────────────────────────
  //  ENEMY AI  –  platform-edge aware patrol
  // ─────────────────────────────────────────────────────────
  updateEnemies() {
    const now = this.time.now;

    this.enemies.getChildren().forEach(e => {
      if (!e.active) return;

      // Wall flip (with cooldown to avoid jitter)
      if ((e.body.blocked.left || e.body.blocked.right) && now - e.lastFlipTime > 300) {
        e.patrolDir   *= -1;
        e.lastFlipTime = now;
      }

      // Edge detection: runs EVERY FRAME when on ground.
      // lookAhead=4px – stops the enemy just before the edge while still leaving
      // enough patrol room even on narrow 2-tile platforms (64px wide).
      if (e.body.blocked.down) {
        const lookX = e.patrolDir > 0 ? e.body.right + 4 : e.body.left - 4;
        const lookY = e.body.bottom + 4;

        let groundAhead = false;
        this.platforms.children.iterate(tile => {
          if (!tile || !tile.active) return;
          const b = tile.body;
          if (lookX >= b.left && lookX <= b.right &&
              lookY >= b.top  && lookY <= b.bottom + TILE) {
            groundAhead = true;
          }
        });

        if (!groundAhead) {
          e.patrolDir   *= -1;
          e.lastFlipTime = now;  // reset wall cooldown too
        }
      }

      e.setVelocityX(70 * e.patrolDir);
      e.setFlipX(e.patrolDir < 0);
    });
  }

  // ─────────────────────────────────────────────────────────
  //  COLLISION CALLBACKS
  // ─────────────────────────────────────────────────────────

  collectCoin(player, coin) {
    coin.destroy();
    this.score += 100;
    this.showFloatingText(coin.x, coin.y, '+100', 0xFFD700);
    this.sound.play('sfx_coin', { volume: 0.7 });
  }

  collectFragment(player, fragment) {
    fragment.destroy();
    this.fragmentsCollected++;
    this.score += 500;
    this.showFloatingText(fragment.x, fragment.y, '+500 ◆', 0xFFEB3B);

    if (this.fragmentsCollected >= FRAGMENTS_TO_WIN && !this.exitOpen) {
      this.openExit();
    }
  }

  /**
   * Stomp  – player falling, feet within top 40% of enemy → kill enemy.
   * Hit    – any other contact → player dies.
   */
  handleEnemyContact(player, enemy) {
    if (!enemy.active) return;

    const falling   = player.body.velocity.y > 60;
    const threshold = enemy.body.height * 0.4;

    if (falling && (player.body.bottom - enemy.body.top) < threshold) {
      this.stompEnemy(enemy);
    } else {
      this.triggerPlayerDeath();
    }
  }

  stompEnemy(enemy) {
    enemy.body.enable = false;
    this.score += 200;
    this.showFloatingText(enemy.x, enemy.y, '+200', 0xFF6B6B);
    this.player.setVelocityY(STOMP_BOUNCE);
    const bsx = enemy.scaleX, bsy = enemy.scaleY;
    this.tweens.add({
      targets: enemy,
      scaleX: bsx * 1.3, scaleY: 0,
      y: enemy.y + 4,
      duration: 120, ease: 'Cubic.easeIn',
      onComplete: () => enemy.destroy()
    });
  }

  reachExit(player, exit) {
    if (!this.exitOpen || this.playerDead) return;
    this.playerDead = true;
    player.setVelocity(0, 0);
    player.body.enable = false;
    this.cameras.main.flash(500, 255, 255, 100);
    this.sound.stopByKey('music');
    this.sound.play('sfx_clear', { volume: 0.8 });

    const nextLevel = this.currentLevel + 1;
    if (nextLevel >= LEVEL_CONFIGS.length) {
      // All levels done → závěrečná obrazovka s žebříčkem
      const finalScore = this.score;
      this.time.delayedCall(900, () => {
        this.registry.set('currentLevel', 0);
        this.scene.stop('UIScene');
        this.scene.start('WinScene', { score: finalScore });
      });
    } else {
      this.showCenterText('LEVEL COMPLETE!', 0x2ECC40);
      this.registry.set('currentLevel', nextLevel);
      this.time.delayedCall(2200, () => this.scene.restart());
    }
  }

  // ─────────────────────────────────────────────────────────
  //  HELPERS
  // ─────────────────────────────────────────────────────────

  openExit() {
    this.exitOpen = true;
    this.exitDoor.setVisible(true);
    this.exitDoor.body.enable = true;
    this.tweens.add({
      targets: this.exitDoor, alpha: 0.2, duration: 220,
      yoyo: true, repeat: 7
    });
    this.showCenterText(this.cfg.unlockMsg, 0x2ECC40);
  }

  triggerPlayerDeath() {
    if (this.playerDead) return;
    this.playerDead = true;
    this.cameras.main.flash(300, 255, 0, 0);
    this.time.delayedCall(350, () => this.scene.restart());
  }

  showFloatingText(x, y, msg, color) {
    const fill = '#' + color.toString(16).padStart(6, '0');
    const txt  = this.add.text(x, y, msg, {
      fontSize: '14px', fill, fontFamily: 'monospace',
      stroke: '#000000', strokeThickness: 3
    }).setOrigin(0.5, 1).setDepth(50);
    this.tweens.add({
      targets: txt, y: y - 44, alpha: 0, duration: 950,
      onComplete: () => txt.destroy()
    });
  }

  showCenterText(msg, color) {
    const fill = '#' + color.toString(16).padStart(6, '0');
    const cx   = this.cameras.main.scrollX + GAME_W / 2;
    const txt  = this.add.text(cx, GAME_H / 2, msg, {
      fontSize: '30px', fill, fontFamily: 'monospace',
      stroke: '#000000', strokeThickness: 5, align: 'center'
    }).setOrigin(0.5).setDepth(100);
    this.time.delayedCall(2100, () => txt.destroy());
  }

  addClouds() {
    // Keshuma misty cloud – layered lavender-purple wisps, no harsh white edges
    const g = this.make.graphics({ x: 0, y: 0, add: false });
    // Outermost soft halo
    g.fillStyle(0x9E88C8, 0.18);
    g.fillEllipse(50, 24, 100, 36);
    // Mid layer
    g.fillStyle(0xBAACD8, 0.32);
    g.fillEllipse(50, 24, 82, 28);
    g.fillEllipse(26, 28, 44, 20);
    g.fillEllipse(74, 28, 44, 20);
    // Inner body
    g.fillStyle(0xD4C8EE, 0.48);
    g.fillEllipse(50, 22, 58, 20);
    g.fillEllipse(28, 26, 32, 15);
    g.fillEllipse(72, 26, 32, 15);
    // Bright core
    g.fillStyle(0xEDE8FF, 0.55);
    g.fillEllipse(50, 21, 34, 13);
    g.generateTexture('cloud', 100, 48);
    g.destroy();

    const cloudYs = [32, 58, 86, 46, 72, 108];
    for (let x = 80; x < WORLD_W; x += 230) {
      const y = cloudYs[Math.floor(Math.random() * cloudYs.length)];
      const alpha = 0.45 + Math.random() * 0.35;
      const scale = 0.65 + Math.random() * 0.85;
      this.add.image(x, y, 'cloud')
        .setScrollFactor(0.25)
        .setAlpha(alpha)
        .setScale(scale);
    }
  }
}

// ─────────────────────────────────────────────────────────────
//  UI SCENE  –  HUD (Score, Fragments, controls hint)
// ─────────────────────────────────────────────────────────────
class UIScene extends Phaser.Scene {
  constructor() { super({ key: 'UIScene', active: false }); }

  create() {
    this.add.rectangle(0, 0, GAME_W, 38, 0x000000, 0.5).setOrigin(0, 0);

    this.levelText = this.add.text(16, 10, 'LEVEL 1', {
      fontSize: '16px', fill: '#AAAAFF', fontFamily: 'monospace',
      stroke: '#000', strokeThickness: 3
    });

    this.scoreText = this.add.text(110, 10, 'SCORE: 0', {
      fontSize: '16px', fill: '#FFFFFF', fontFamily: 'monospace',
      stroke: '#000', strokeThickness: 3
    });

    this.fragText = this.add.text(310, 10, '◆ FRAGMENTS: 0 / ' + FRAGMENTS_TO_WIN, {
      fontSize: '16px', fill: '#FFD700', fontFamily: 'monospace',
      stroke: '#000', strokeThickness: 3
    });

    this.helpText = this.add.text(GAME_W - 16, 10, '← → move  ↑/SPACE jump', {
      fontSize: '12px', fill: '#CCCCCC', fontFamily: 'monospace'
    }).setOrigin(1, 0);
  }

  setGameScene(scene) {
    this.gameScene = scene;
  }

  update() {
    if (!this.gameScene) return;
    const lvl = (this.registry.get('currentLevel') ?? 0) + 1;
    this.levelText.setText('LEVEL ' + lvl);
    this.scoreText.setText('SCORE: ' + this.gameScene.score);
    this.fragText.setText('◆ FRAGMENTS: ' + this.gameScene.fragmentsCollected + ' / ' + FRAGMENTS_TO_WIN);
    this.fragText.setColor(this.gameScene.exitOpen ? '#2ECC40' : '#FFD700');
  }
}

// ─────────────────────────────────────────────────────────────
//  WIN SCENE  –  závěrečná obrazovka po dohrání všech levelů
// ─────────────────────────────────────────────────────────────
class WinScene extends Phaser.Scene {
  constructor() { super({ key: 'WinScene' }); }

  init(data) {
    this.finalScore = data.score ?? 0;
    this.submitted  = false;
  }

  create() {
    const W  = this.scale.width;
    const H  = this.scale.height;
    const cx = W / 2;

    // Tmavé pozadí s hvězdičkami
    this.add.rectangle(cx, H / 2, W, H, 0x08081a);
    for (let i = 0; i < 70; i++) {
      const sx = Phaser.Math.Between(0, W);
      const sy = Phaser.Math.Between(0, H);
      this.add.circle(sx, sy, Math.random() > 0.85 ? 2 : 1,
        0xffffff, Phaser.Math.FloatBetween(0.3, 1));
    }

    // Nadpis
    this.add.text(cx, 26, 'FINAL BOSU DEFEATED!', {
      fontSize: '24px', fill: '#FFD700', fontFamily: 'monospace',
      stroke: '#000', strokeThickness: 5
    }).setOrigin(0.5);

    // Skóre hráče
    this.add.text(cx, 58, 'Your score:  ' + this.finalScore.toLocaleString('en-US'), {
      fontSize: '14px', fill: '#ffffff', fontFamily: 'monospace'
    }).setOrigin(0.5);

    // Kontejner pro žebříček (bude překreslen po načtení/odeslání)
    this.lbGroup = this.add.container(0, 0);

    const labelY = H - 68;

    // Show the plain HTML input overlay, aligned to canvas position
    const overlay = document.getElementById('win-input-overlay');
    if (overlay) {
      const canvas = document.querySelector('canvas');
      if (canvas) {
        const r = canvas.getBoundingClientRect();
        overlay.style.position  = 'fixed';
        overlay.style.left      = (r.left + r.width / 2) + 'px';
        overlay.style.top       = (r.top + H - 98) + 'px';
        overlay.style.transform = 'translateX(-50%)';
      }
      overlay.style.display = 'block';
    }
    const inputEl = document.getElementById('winName');
    if (inputEl) { inputEl.value = ''; inputEl.style.borderColor = '#4455cc'; inputEl.focus(); }

    this.submitBtn = this.add.text(cx, labelY + 20, '[ SUBMIT SCORE ]', {
      fontSize: '15px', fill: '#2ECC40', fontFamily: 'monospace',
      stroke: '#000', strokeThickness: 3
    }).setOrigin(0.5).setInteractive({ useHandCursor: true })
      .on('pointerover',  () => this.submitBtn.setFill('#55ff66'))
      .on('pointerout',   () => this.submitBtn.setFill('#2ECC40'))
      .on('pointerdown',  () => this._submit());

    this.restartBtn = this.add.text(cx, labelY + 50, '[ PLAY AGAIN ]', {
      fontSize: '15px', fill: '#4488ff', fontFamily: 'monospace',
      stroke: '#000', strokeThickness: 3
    }).setOrigin(0.5).setInteractive({ useHandCursor: true })
      .on('pointerover',  () => this.restartBtn.setFill('#88aaff'))
      .on('pointerout',   () => this.restartBtn.setFill('#4488ff'))
      .on('pointerdown',  () => {
        this.scene.start('TitleScene');
      }).setVisible(false);

    // Načti aktuální žebříček
    this._renderLeaderboard([], null, null);
    this._fetchLeaderboard();
  }

  // ── Vykreslí žebříček ──────────────────────────────────────
  _renderLeaderboard(top10, playerRank, playerEntry) {
    this.lbGroup.removeAll(true);

    const W   = this.scale.width;
    const cx  = W / 2;
    const COL = 340;          // šířka tabulky
    const x0  = cx - COL / 2;
    const y0  = 80;
    const ROW = 18;

    // Nadpis sekce
    this.lbGroup.add(
      this.add.text(cx, y0, '─── TOP 10 LEADERBOARD ───', {
        fontSize: '13px', fill: '#FFD700', fontFamily: 'monospace',
        stroke: '#000', strokeThickness: 3
      }).setOrigin(0.5)
    );

    if (top10.length === 0) {
      this.lbGroup.add(
        this.add.text(cx, y0 + ROW + 4, 'Loading...', {
          fontSize: '12px', fill: '#555', fontFamily: 'monospace'
        }).setOrigin(0.5)
      );
      return;
    }

    const inTop10 = playerRank !== null && playerRank <= 10;

    top10.forEach((entry, i) => {
      const rank  = i + 1;
      const isMe  = playerEntry &&
                    entry.name  === playerEntry.name &&
                    entry.score === playerEntry.score;
      const y     = y0 + ROW + i * ROW + 4;

      // Barevné odlišení
      const col   = isMe     ? '#FFD700'
                  : rank <= 3 ? '#ffffff'
                  : '#999999';

      const prefix = isMe ? '▶ ' : '  ';
      const rankStr  = String(rank).padStart(2);
      const nameStr  = entry.name.padEnd(16);
      const scoreStr = entry.score.toLocaleString('en-US').padStart(8);

      this.lbGroup.add(
        this.add.text(x0 + 8, y, `${prefix}${rankStr}. ${nameStr} ${scoreStr}`, {
          fontSize: '12px', fill: col, fontFamily: 'monospace'
        })
      );
    });

    // Hráč mimo top 10
    if (playerRank !== null && !inTop10 && playerEntry) {
      const sepY  = y0 + ROW + 10 * ROW + 8;
      const lineY = sepY + 14;

      this.lbGroup.add(
        this.add.text(cx, sepY, '· · ·', {
          fontSize: '11px', fill: '#444', fontFamily: 'monospace'
        }).setOrigin(0.5)
      );

      const rankStr  = String(playerRank).padStart(2);
      const nameStr  = playerEntry.name.padEnd(16);
      const scoreStr = playerEntry.score.toLocaleString('en-US').padStart(8);

      this.lbGroup.add(
        this.add.text(x0 + 8, lineY, `▶ ${rankStr}. ${nameStr} ${scoreStr}`, {
          fontSize: '12px', fill: '#FFD700', fontFamily: 'monospace'
        })
      );
    }
  }

  // ── Načte aktuální top 10 ──────────────────────────────────
  _sbHeaders() {
    return {
      'apikey':        SUPABASE_ANON_KEY,
      'Authorization': 'Bearer ' + SUPABASE_ANON_KEY,
      'Content-Type':  'application/json'
    };
  }

  _fetchLeaderboard() {
    fetch(`${SUPABASE_URL}/rest/v1/scores?select=name,score&order=score.desc&limit=10`, {
      headers: this._sbHeaders()
    })
      .then(r => r.json())
      .then(top10 => this._renderLeaderboard(top10, null, null))
      .catch(() => {});
  }

  // ── Odešle skóre ──────────────────────────────────────────
  _submit() {
    if (this.submitted) return;
    const el   = document.getElementById('winName');
    const name = el ? el.value.trim() : '';

    if (!name) {
      if (el) el.style.borderColor = '#ff4444';
      return;
    }

    this.submitted = true;
    this.submitBtn.setText('Submitting...').disableInteractive();

    const entry = { name: String(name).trim().slice(0, 20), score: Math.floor(this.finalScore) };

    // 1. vlož skóre
    fetch(`${SUPABASE_URL}/rest/v1/scores`, {
      method:  'POST',
      headers: this._sbHeaders(),
      body:    JSON.stringify(entry)
    })
    // 2. načti top 10
    .then(() => fetch(`${SUPABASE_URL}/rest/v1/scores?select=name,score&order=score.desc&limit=10`, {
      headers: this._sbHeaders()
    }))
    .then(r => r.json())
    .then(top10 => {
      // rank = počet skóre >= moje skóre (včetně)
      const rank = top10.filter(e => e.score >= entry.score).length || 1;
      this._renderLeaderboard(top10, rank, entry);
      const ov = document.getElementById('win-input-overlay');
      if (ov) ov.style.display = 'none';
      this.submitBtn.setVisible(false);
      this.restartBtn.setVisible(true);
    })
    .catch(() => {
      this.submitBtn.setText('[ Connection error ]').setInteractive({ useHandCursor: true });
      this.submitted = false;
    });
  }

  shutdown() {
    const ov = document.getElementById('win-input-overlay');
    if (ov) ov.style.display = 'none';
  }
}

// ─────────────────────────────────────────────────────────────
//  PHASER CONFIG  –  must come AFTER all class definitions
// ─────────────────────────────────────────────────────────────
const config = {
  type: Phaser.AUTO,
  width:  GAME_W,
  height: GAME_H,
  backgroundColor: '#5c94fc',
  pixelArt: true,
  fps: { forceSetTimeOut: true },
  physics: {
    default: 'arcade',
    arcade: { gravity: { y: GRAVITY }, debug: false }
  },
  scene: [BootScene, TitleScene, GameScene, UIScene, WinScene]
};

window.game = new Phaser.Game(config);
